<?php
/**
 * Created by PhpStorm.
 * User: genady
 * Date: 6/6/17
 * Time: 8:43 PM
 */

namespace Applications\Modules;



use system\MainModel;

class AdminModel extends MainModel
{
    public function Index(){

    }
 function getPageData()
{


     // TODO: Change the autogenerated stub
    $page_data = array('page'=> 'admin_page',
                       'header_admin_menu' => $this->getHeaderMenu());

    return $page_data;
}
private function getHeaderMenu(){
        ob_start();
        require_once 'header_admin_menu.php';
        return ob_get_clean();
}
}